name       : czkawka
version    : 6.0.0
release    : 4
source     :
    - https://github.com/qarmin/czkawka/archive/refs/tags/6.0.0.tar.gz : 32dc1d8a55bc3ce478246830a1f81679affa85735e69aa049fd83e30271e368f
homepage   : https://qarmin.github.io/czkawka/
license    :
    - CC-BY-4.0
    - MIT
component  : system.utils
summary    : Multi functional app to find duplicates, empty folders, similar images etc
description: |
    Czkawka is a simple, fast and free app to remove unnecessary files from your computer.
    It's an alternative for fslint.
networking : yes
builddeps  :
    - pkgconfig(gtk4)
    - cargo
build      : |
    cargo build --release --workspace
install    : |
    install -Dm00755 target/release/czkawka_gui $installdir/usr/bin/czkawka_gui
    install -Dm00755 target/release/czkawka_cli $installdir/usr/bin/czkawka_cli
    install -Dm00644 data/com.github.qarmin.czkawka.desktop -t $installdir/usr/share/applications
    install -Dm00644 data/icons/*.svg -t $installdir/usr/share/icons/hicolor/scalable/apps
    install -Dm00644 data/com.github.qarmin.czkawka.metainfo.xml -t $installdir/usr/share/metainfo
