name       : czkawka
version    : 4.1.0
release    : 1
source     :
    - https://github.com/qarmin/czkawka/archive/refs/tags/4.1.0.tar.gz : 3399a2878554692fd00b16226248727bdcf1188d247d584d28ded35800fb42ba
homepage   : https://github.com/qarmin/czkawka
license    : MIT
component  : system.utils
summary    : Multi functional app to find duplicates, empty folders, similar images etc
description: |
    Czkawka is a simple, fast and free app to remove unnecessary files from your computer.
    It's an alternative for fslint.
networking : yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/czkawka_gui $installdir/usr/bin/czkawka_gui
    install -Dm00755 target/release/czkawka_cli $installdir/usr/bin/czkawka_cli
    install -Dm00644 data/com.github.qarmin.czkawka.desktop -t $installdir/usr/share/applications
    install -Dm00644 data/icons/*.svg -t $installdir/usr/share/icons/hicolor/scalable/apps
    install -Dm00644 data/com.github.qarmin.czkawka.metainfo.xml -t $installdir/usr/share/metainfo