name       : czkawka
version    : 5.1.0
release    : 2
source     :
    - https://github.com/qarmin/czkawka/archive/refs/tags/5.1.0.tar.gz : 346c256ef215fa029a78c8150fcac1815e0c7f98319a167e18c5239e04849068
homepage   : https://qarmin.github.io/czkawka/
license    :
    - CC-BY-4.0
    - MIT
component  : system.utils
summary    : Multi functional app to find duplicates, empty folders, similar images etc
description: |
    Czkawka is a simple, fast and free app to remove unnecessary files from your computer.
    It's an alternative for fslint.
networking : yes
builddeps  :
    - pkgconfig(gtk4)
    - cargo
build      : |
    cargo build --release --workspace
install    : |
    install -Dm00755 target/release/czkawka_gui $installdir/usr/bin/czkawka_gui
    install -Dm00755 target/release/czkawka_cli $installdir/usr/bin/czkawka_cli
    install -Dm00644 data/com.github.qarmin.czkawka.desktop -t $installdir/usr/share/applications
    install -Dm00644 data/icons/*.svg -t $installdir/usr/share/icons/hicolor/scalable/apps
    install -Dm00644 data/com.github.qarmin.czkawka.metainfo.xml -t $installdir/usr/share/metainfo